<?php

return [
	'tipo_plantilla' => [
		'alerta' => 'Alerta',
		'despacho_produccion' => 'Despacho Producción',
		'detalle_compra' => 'Detalle Compra',
		'detalle_gasto_compra' => 'Detalle de Gastos de Compras',
		'devolucion_formula' => 'Devolución Mezcla',
		'devolucion_producto_terminado' => 'Devolución Producto Terminado',
		'egreso_desperdicio' => 'Egreso de desperdicio',
		'egreso_planta' => 'Egreso de Planta',
		'egreso_planta_historial' => 'Egreso de Planta Historial',
		'etiqueta_compra' => 'Etiqueta Compra',
		'etiqueta_devolucion_mezcla' => 'Etiqueta Devolución Mezcla',
		'etiqueta_molino' => 'Etiqueta Molino',
		'etiqueta_paleta' => 'Etiqueta Paleta',
		'etiqueta_producto' => 'Etiqueta Producto',
		'generar_desperdicio' => 'Generar Desperdicio',
		'generar_percha' => 'Generar Percha',
		'ingreso_producto_terminado' => 'Ingreso Producto Terminado',
		'inventario_material' => 'Inventario Material',
		'inventario_producto_terminado' => 'Inventario Producto Terminado',
		'lista_embarque' => 'Lista de Embarque',
		'mezclas' => 'Mezclas',
		'notificaciones_clientes_inactivos' => 'Notificaciones Clientes Inactivos',
		'notificaciones_devolucion_producto_terminado' => 'Notificaciones Devolución Producto Terminado',
		'notificaciones_falta_stock_material' => 'Notificaciones Falta Stock Material',
		'notificaciones_fin_orden_extrusion' => 'Notificaciones Fin de Orden de Extrusión',
		'notificaciones_stock' => 'Notificaciones de Stock Minimo',
		'notificaciones_verificacion_inventario' => 'Notificaciones Verificación Inventario',
		'produccion_diaria_corte_bobinado' => 'Producción Diaria Corte Bobinado',
		'reingreso_produccion' => 'Reingreso Producción',
		'resumen_produccion_bobinado' => 'Resumen Producción Bobinado',
		'resumen_produccion_corte' => 'Resumen Producción Corte',
		'resumen_produccion_extrusion' => 'Resumen Producción Extrusión',
		'solicitud_compra' => 'Solicitud de Compra',
		'transformar_rollos' => 'Transformar Rollos',
		'ventas_consolidado' => 'Ventas Consolidado',
		'ventas_detallado' => 'Ventas Datallado',
		'verificacion_inventario' => 'Verificación Inventario',
	]

];